simplifies logic

diff --git a/git_clone_find b/git_clone_find
--- a/git_clone_find
+++ b/git_clone_find
@@ -64,40 +64,37 @@ EOF
     arguments+=("$argument")
   done
 
-  repo_name_url=$(get_argument 0)
+  repo_ssh_url=$(get_argument 0)
   folder_name=$(get_argument 1)
 
-  if [ -z "$repo_name_url" ]; then
+  if [ -z "$repo_ssh_url" ]; then
     print_help
     return
   fi
 
-  if [[ $repo_name_url =~ ^git@ ]]; then
+  if [[ $repo_ssh_url =~ ^git@ ]]; then
     if [[ -z "$folder_name" ]]; then
-      final_folder_name="$(basename "$repo_name_url" | sed -e 's/\.git//g')"
-    else
-      final_folder_name="$folder_name"
+      folder_name="$(basename "$repo_ssh_url" | sed -e 's/\.git//g')"
     fi
 
     verbose=true
-    git_clone "$repo_name_url" "$final_folder_name" && cd "$final_folder_name" || return
+    git_clone "$repo_ssh_url" "$folder_name" && cd "$folder_name" || return
     return
   fi
 
-  split_repo_name="$(echo "$repo_name_url" | awk -F "/" '{print $2}')"
+  repo_id="$repo_ssh_url"
+  split_repo_name="$(echo "$repo_id" | awk -F "/" '{print $2}')"
 
   if [ "$split_repo_name" != '' ]; then
     if [[ -z "$folder_name" ]]; then
-      final_folder_name="$split_repo_name"
-    else
-      final_folder_name="$folder_name"
+      folder_name="$split_repo_name"
     fi
 
-    clone_url="git@github.com:$repo_name_url.git"
-    log "Trying $clone_url. \e[2mCloning into $final_folder_name.\e[0m"
+    clone_url="git@github.com:$repo_id.git"
+    log "Trying $clone_url. \e[2mCloning into $folder_name.\e[0m"
 
     verbose=true
-    git_clone "$clone_url" "$final_folder_name" && cd "$final_folder_name" || return
+    git_clone "$clone_url" "$folder_name" && cd "$folder_name" || return
     return
   fi
 
@@ -106,21 +103,21 @@ EOF
     return
   fi
 
+  repo_name="$repo_id"
+
   if [[ -z "$folder_name" ]]; then
-    final_folder_name="$repo_name_url"
-  else
-    final_folder_name="$folder_name"
+    folder_name="$repo_name"
   fi
 
   for username in "${GCF_GITHUB_USERNAMES[@]}"; do
-    clone_url="git@github.com:$username/$repo_name_url.git"
-    log "Trying $clone_url. \e[2mCloning into $final_folder_name.\e[0m"
+    clone_url="git@github.com:$username/$repo_name.git"
+    log "Trying $clone_url. \e[2mCloning into $folder_name.\e[0m"
 
-    if git_clone "$clone_url" "$final_folder_name"; then
-      cd "$final_folder_name" || return
+    if git_clone "$clone_url" "$folder_name"; then
+      cd "$folder_name" || return
       return
     fi
   done
 
-  log "$repo_name_url could not be cloned. This usually means the repository could not be found. Run the command again with the --verbose flag for more info."
+  log "$repo_name could not be cloned. This usually means the repository could not be found. Run the command again with the --verbose flag for more info."
 }
